services:
  - type: web
    name: dimafarm-app
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    autoDeploy: true
    envVars:
      - key: PORT
        value: 10000
